name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
    DOCKER_TAG: "$(date +%Y%m%d%H%M%S)"
    
jobs:

  refresh_container:
    environment: snyk_aws_demo
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILDKIT: "1"
      DOCKER_LOGIN: "${{ secrets.DOCKER_LOGIN }}"
      DOCKER_PASSWORD: "${{ secrets.DOCKER_PASSWORD }}"
      SNYK_TOKEN: "${{ secrets.SNYK_TOKEN }}"
    steps:
    - uses: actions/checkout@v1
    - name: update_container_image_rebuild_scan_push
      run: |
        docker build . --file Dockerfile --tag lucmaeda/my-snyk-demo-mvn-goof:$DOCKER_TAG
        docker run --env SNYK_TOKEN -v /var/run/docker.sock:/var/run/docker.sock snyk/snyk:docker snyk container test --print-deps --org=demo_high --project-name=${{github.repository}} --app-vulns --nested-jars-depth=8 lucmaeda/my-snyk-demo-mvn-goof:$DOCKER_TAG || true
