name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    environment: snyk_aws_demo
    env:
      DOCKER_BUILDKIT: "1"
      DOCKER_IMAGETAG: "20220703174337"
      DOCKER_LOGIN: "${{ secrets.DOCKER_LOGIN }}"
      DOCKER_PASSWORD: "${{ secrets.DOCKER_PASSWORD }}"
      SNYK_TOKEN: "${{ secrets.SNYK_TOKEN }}"
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag lucmaeda/my-snyk-demo-mvn-goof:$DOCKER_IMAGETAG
    - name: Vulnerability scan with Snyk Container
      run: docker run --env SNYK_TOKEN -v /var/run/docker.sock:/var/run/docker.sock snyk/snyk:docker snyk container test --print-deps --org=demo_high --project-name=${{github.repository}} --app-vulns --nested-jars-depth=8 lucmaeda/my-snyk-demo-mvn-goof:$DOCKER_IMAGETAG
