name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  refresh_container:
    environment: snyk_aws_demo
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILDKIT: "1"
      DOCKER_LOGIN: "lucmaeda"
      DOCKER_PASSWORD: "${{ secrets.DOCKER_PASSWORD }}"
      SNYK_TOKEN: "${{ secrets.SNYK_TOKEN }}"
    steps:
    - uses: actions/checkout@v1
    - name: build container image
      run: docker build . --file Dockerfile --tag lucmaeda/my-snyk-demo-mvn-goof:$GITHUB_RUN_NUMBER
    - name: scan vulnerability
      run: docker run --env SNYK_TOKEN -v /var/run/docker.sock:/var/run/docker.sock snyk/snyk:docker snyk container test --print-deps --org=demo_high --project-name=${{github.repository}} --app-vulns --nested-jars-depth=8 ${{env.DOCKER_LOGIN}}/my-snyk-demo-mvn-goof:$GITHUB_RUN_NUMBER || true
    - name: monitor container image for vulnerability
      run: docker run --env SNYK_TOKEN -v /var/run/docker.sock:/var/run/docker.sock snyk/snyk:docker snyk container monitor --print-deps --org=demo_high --project-name=${{github.repository}} --app-vulns --nested-jars-depth=8 ${{env.DOCKER_LOGIN}}/my-snyk-demo-mvn-goof:$GITHUB_RUN_NUMBER
    - name: push container image
      run: docker push ${{env.DOCKER_LOGIN}}/my-snyk-demo-mvn-goof:$GITHUB_RUN_NUMBER
