name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: DOCKER_BUILDKIT=1 docker build . --file Dockerfile --tag my-snyk-demo-mvn-goof:$(date +%s)
    - name: Vulnerability scan with Snyk Container
      env:
        SNYK_TOKEN: "${{ secrets.SNYK_TOKEN }}"
        DOCKER_LOGIN: "${{ secrets.DOCKER_LOGIN }}"
        DOCKER_PASSWORD: "${{ secrets.DOCKER_PASSWORD }}"
      run: |
        echo "test 01: $DOCKER_LOGIN"
        echo "test 02: ${{env.DOCKER_LOGIN}}"
        echo "test 03: ${DOCKER_LOGIN}"
        SNYK_TOKEN=$SNYK_TOKEN docker run --env SNYK_TOKEN -v /var/run/docker.sock:/var/run/docker.sock snyk/snyk:docker snyk container test --print-deps --org=demo_high --project-name=${{github.repository}} --app-vulns --nested-jars-depth=8 lucmaeda/my-snyk-demo-mvn-goof:$(date +%s)
